version: 2
jobs:
  build:
    working_directory: ~/tasmocompiler
    docker:
      - image: circleci/node:12.16.2-buster      
    steps:
      - checkout
      - node/install:
          install-npm: false
          node-version: 12.16.2
      - node/install-yarn:
          version: 1.22.4
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: lint
          command: yarn lint
